name: Build & Release Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install dependencies # Not needed for this project
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Build Chrome Extension
        run: |
          python Tools/build_extension.py

      - name: Zip extension files
        run: |
          cd dist/extension
          zip -r ../../extension.zip .
          cd ../..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Auto Release - ${{ github.sha }}
          tag_name: auto-${{ github.sha }}
          files: extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
