name: Deploy to Firebase Hosting on merge
'on':
  push:
      paths:
        - 'public/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHKOLOTWEAKS }}'
          channelId: live
          projectId: shkolotweaks
